kind: Service
apiVersion: v1
metadata:
  name: ingress
  namespace: demo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: http
  selector:
    app: ingress
