apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: ingress
  namespace: demo
  labels:
    app: ingress
spec:
  meshName: "appmesh"
  listeners:
    - portMapping:
        port: 444
        protocol: http
  serviceDiscovery:
    dns:
      hostName: ingress.demo
  backends:
    - virtualService:
        virtualServiceName: podinfo.demo
