apiVersion: v1
kind: Service
metadata:
  labels:
    app: flagger-loadtester
  name: flagger-loadtester
  namespace: prod
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: flagger-loadtester
  type: ClusterIP
