apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: appmesh-inject
  namespace: appmesh-system
spec:
  releaseName: appmesh-inject
  chart:
    git: https://github.com/aws/eks-charts
    ref: master
    path: stable/appmesh-inject
  values:
    mesh:
      create: true
      name: "appmesh"
      discovery: dns
