apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: appmesh-controller
  namespace: appmesh-system
spec:
  releaseName: appmesh-controller
  chart:
    git: https://github.com/aws/eks-charts
    ref: master
    path: stable/appmesh-controller
  values:
    image:
      repository: 352684330888.dkr.ecr.us-west-2.amazonaws.com/amazon/app-mesh-controller
      tag: cache-vn
