apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: flagger-loadtester
  namespace: demo
  labels:
    app: flagger-loadtester
spec:
  meshName: "appmesh"
  listeners:
    - portMapping:
        port: 444
        protocol: http
  serviceDiscovery:
    dns:
      hostName: flagger-loadtester.demo
  backends:
    - virtualService:
        virtualServiceName: podinfo.demo
    - virtualService:
        virtualServiceName: podinfo-canary.demo
