---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUNjI6GsHmEuyfLVIBPfiEAtIDgIUwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMDI5MTAwOTAwWhcNMjQxMDI3MTAwOTAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AMNOSzTgsOHLC9KSdxDhnDGz3N0SrmKizd94ewwef6fDcn/f+/DiW2pRBfdYQDfv
    s5XwA5tFDSKc1o4/1bD57YCtu0fBKg3rD8iruGH44C0HlYB2KLLL59eOefEhvdAP
    UGJwN+GNyFCLGjMtXBg77/LHduWfFn7gSsIeU+wKOvmhM/p/miHrh0JZ+WBAQWW/
    pICERH70CxR8p3RdCU+ehI6C1wooeGpN3loQsppuN8m5aWWDKkEdM9FHrBImkfZe
    IsLyXIiuxiW/QsbxGiSbDs3jxJwTVhPqrlBRAWioeVtqcL867XcjyLSKRBj/jngt
    RoDdd+Q90SSfFwzm+TzGWFLgxkx8g6DCkOQM7bzdryA+gXdkFZPAiXMYcQhob8YW
    VxzXz9wtx7TgGVf3Ui8M8Mdqitvcy5PGz9KuEkQnw/zAQJOMgITP9Dj/a1RgfSeS
    pWJUhz1dOp3aCBDoiwqFDBpOHCgBXJfCqK27L3Q3DaEq5BnTsuC9spDxWKz2Z/eE
    MOVtwRFcy3w/2dS12jLWk2eoyaPTFCpLARn5HGLoJG7k1wBGa5JpgVt89hUh262y
    UI4Wx36xUMBnUjJ2hi1Das7ZEidjym72KOHA+H5JstnltA181fa+fhixmTMD4v+A
    nYkUmnbOuafE5JVYvWizT1YQ44rzGMvoeNU/kJLYu6LVAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSBupi/Osqwvhf4
    OPytl7qZiekZljANBgkqhkiG9w0BAQ0FAAOCAgEAOssTRvG8oWmzPDW8Gj2hjkrS
    sl16UXuTMQlQQ5op1cXQn2r/ZXNamw5StichMYRICRMFWUK1NoyRa2Pc6UICRmM1
    hxtDkF7wI8HQRozM9fo4UT+C+rbHD5xFLynoljFg0mflmElg/i1Yhq8QOBltSVkl
    00f/N7tWpoVVc3R++Woh8LUtGGVt8tmuX7gK/4kbrjvMaqPvQwYmMf2Kqnhxw7/U
    Y0BEEAwFRHn1cCA32P6aIxW1g+qCsq12QZPYPOaPU+HlDSB5SnCZIQpf5uY032Rv
    PynxSjUoH5c8x7gdnqPwFWNkwdio4sFJWil7Ozy6D8Sh4nnIr1qFC4fhJGzPI5L6
    RGhqJ1ulWALYohj/nrY/R2ZeYEnaeafUBmA+oAj78PmxWhNP8onQk1eJvHpyNTHH
    Dusf1C7yVoUg+n09wcIvrxSzngz4qXQ91QDl9+Gzz36reRNbMXi1A57MshsasZQo
    B42+cVq0vU1rTZ2OKUF21eGdH3/BFcNnLeL28MSgg1JGVKm/ASqM/6VjFAdSIB4n
    fgcwcjmAAiKpW4jEoEDyvFS1KqpYC6XLBaSJ6MD2bcZIafKAtfW18QZcJWXOWVHr
    /FfnPS2YAObxno3vQWMosIjFjLI5nOuPl6e28v8I5PbZzaqy1S5avwMKhVZ6VDwF
    qL0qlnVGk8yj4e6NbTs=
    -----END CERTIFICATE-----
    
